export const DELETE_ADVICE = 'DELETE_ADVICE';
export const GET_ADVICE_REQUEST = 'GET_ADVICE_REQUEST';
export const GET_ADVICE_SUCCESS = 'GET_ADVICE_SUCCESS';
export const GET_ADVICE_ERROR = 'GET_ADVICE_ERROR';
